#!/bin/sh

# title			:cmushnotify
# version		:1.0
# url			:https://github.com/Dimithrandir/cmushnotify
# author		:Dimithrandir
# description	:Sends notifications from cmus. Only fires a notification if a new song started playing after 1/4 of the duration of the previous song, to prevent notification stacking or manual playback notifications.

# Look for album art photos in the same folder as file provided as argument in this order: folder, cover, albumart, (front). If none found, try to extract embedded cover with ffmpeg. If none found, use default pic.
albumart() {
	local dir_name=$( dirname "$1" )
	local names=(folder cover albumart front)
	for item in "${names[@]}" ; do
		img_folder=$( find "$dir_name" -maxdepth 1 -iregex ".*$item*\.\(jpg\|jpeg\|gif\|png\|\)$" -print -quit )
		[ -n "$img_folder" ] && break
	done
	[ -z "$img_folder" ] &&	ffmpeg -i "$1" -an -vcodec copy "$HOME/.config/cmus/.cmushnotify-cover.jpg" -y && img_folder="$HOME/.config/cmus/.cmushnotify-cover.jpg"
	[ -z "$img_folder" ] && img_folder="media-optical-symbolic"
}

[ $# -eq 0 ] && exit 0

if [ $2 = 'playing' ] ; then
	# get all arguments
	while [ $# -ge 2 ] ; do
		eval _$1='$2'
		shift
		shift
	done

	readonly tempfile="$HOME/.config/cmus/.cmushnotify.cache"

	[ -f "$tempfile" ] && timegoal=$( cat "$tempfile" ) || timegoal=0

	if [ $( date +%s ) -ge $timegoal ] ; then
		let "timegoal=$( date +%s )+$_duration/4"
		echo $timegoal > "$tempfile"
		# get album art
		albumart "$_file"
		# send notification
		notify-send -i "$img_folder" "Cmus • Now playing" "$_title\n$_artist\n$_album\n$_date"
	fi
fi
